version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: detailed
    filename: logs/app.log
    when: "D"
    interval: 3
    backupCount: 5

loggers:
  app_logger:
    level: INFO
    handlers: []
    propagate: no

root:
  level: DEBUG
  handlers: [file_handler]
